nodeLinker: pnp
pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    npmAuthToken: "78327E66-6E0F-46A3-81DA-DE47FD4C6371"

npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/

enableTelemetry: false

enableColors:       ${GRADLE_YARNRC:-true}
enableMessageNames: ${GRADLE_YARNRC:-true}
enableProgressBars: ${GRADLE_YARNRC:-true}

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  "@risingstack/react-easy-state@*":
    dependencies:
      react-dom: "*"